Fix round on win, missing only in old compiler
```
v7.c(3892): error C2491: 'round' : definition of dllimport function not allowed [C:\projects\v7\v7.proj]
```